spring:
  datasource:
    url: jdbc:postgresql://stockpulsedb_8l5y_user:R69stKhxf0rOqZxlf9pha3nWGQY6sZKQ@dpg-d8uic73tqb8s73bajpe0-a:5432.singapore-postgres.render.com:5432/stockpulsedb_8l5y
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com.singapore-postgres.render.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

gemini:
  api:
    key: ${GEMINI_API_KEY}